BINANCE_API_KEY = "<SET_ME>"
BINANCE_API_SECRET = "<SET_ME>"
BINANCE_SECRET_KEY = BINANCE_API_SECRET  # для сумісності зі старим кодом

TELEGRAM_TOKEN = "<SET_ME>"
TELEGRAM_CHAT_ID = "465786073"
OPENAI_API_KEY = "<SET_ME>"

CONVERT_SCORE_THRESHOLD = 0.01

CHAT_ID = TELEGRAM_CHAT_ID
