# Fill locally, DO NOT COMMIT real keys!
BINANCE_API_KEY = "YOUR_KEY_HERE"
BINANCE_SECRET_KEY = "YOUR_SECRET_HERE"  # used for HMAC signatures
BINANCE_API_SECRET = BINANCE_SECRET_KEY  # legacy alias
OPENAI_API_KEY    = ""
