name: Daily Report

on:
  schedule:
    - cron: '0 6 * * *'  # 09:00 за Києвом
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Check .env presence
      run: |
        if [ ! -f .env ]; then echo "❌ .env файл не знайдено!"; exit 1; fi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run daily_analysis
      run: |
        export $(cat .env | xargs)
        python3 daily_analysis.py >> daily.log 2>&1
