name: Daily Crypto Analysis

on:
  schedule:
    - cron: '0 6 * * *'  # 09:00 за Києвом (UTC+3)
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🔐 Export Secrets to ENV
        run: |
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "BINANCE_API_KEY=${{ secrets.BINANCE_API_KEY }}" >> $GITHUB_ENV
          echo "BINANCE_SECRET_KEY=${{ secrets.BINANCE_SECRET_KEY }}" >> $GITHUB_ENV
          echo "ADMIN_CHAT_ID=${{ secrets.ADMIN_CHAT_ID }}" >> $GITHUB_ENV

      - name: 🚀 Run daily_analysis.py
        run: python daily_analysis.py
