[tool.ruff]
target-version = "py310"
line-length = 120

[tool.ruff.lint]
select = ["F", "E", "W", "B"]
ignore = ["E402", "E501"]  # E402 — імпорти не зверху; E501 — довгі рядки

[tool.ruff.lint.per-file-ignores]
"src/strategy/selector.py" = ["F821", "E701", "F401"]
